services:
  db:
    ports:
      - 5432:5432
      
  backend:
    restart: no
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]