services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/var/lib/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db

  backend:
    build: ./backend
    image: alexandreamat/quartos-backend:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db
    volumes:
      - ./backend/http_cache.sqlite:/app/http_cache.sqlite
    
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: alexandreamat/quartos-nginx:latest
    depends_on:
      - backend
      - adminer
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443