services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/var/lib/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    image: alexandreamat/quartos:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db
    ports:
      - 8000:80

  # nginx:
  #   image: nginx
  #   restart: always
  #   volumes:
  #     - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./nginx/etc/nginx/nginx.d:/etc/nginx/nginx.d
  #   ports:
  #     - 80:80
  #     - 443:443
  #   depends_on:
  #     - backend