services:
  db:
    restart: no
    ports:
      - 5432:5432

  backend:
    restart: no
    volumes:
      - ./backend:/app
    ports:
      - 8000:80
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "80",
        "--reload",
        "--root-path",
        "/api"
      ]

  frontend:
    build: ./frontend
    restart: no
    volumes:
      - ./frontend:/app

  nginx:
    depends_on:
      - frontend
    volumes:
      - ./nginx/etc/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf

  codegen:
    build: ./frontend
    depends_on:
      - nginx
    volumes:
      - ./backend:/backend
      - ./frontend:/app
    command: [ "npm", "run", "codegen:watch" ]
