services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./db/var/lib/postgresql/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./backend
    image: alexandreamat/quartos-backend:latest
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: alexandreamat/quartos-nginx:latest
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443