site_name: QuartOS
copyright: Copyright (C) 2024 Alexandre Amat
repo_url: https://github.com/alexandreamat/QuartOS
repo_name: alexandreamat/QuartOS
nav:
  - Home: index.md
  - Setup: setup.md
  - Architecture: architecture.md
  - License: license.md
theme:
  name: material
  icon:
    logo: material/cached
    repo: fontawesome/brands/github
  features:
    - navigation.instant
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
extra:
  generator: false
strict: true
use_directory_urls: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
