"""add buckets 2

Revision ID: 028ff3b73c20
Revises: 3551606418b9
Create Date: 2024-03-28 16:00:41.274376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "028ff3b73c20"
down_revision: Union[str, None] = "3551606418b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bucket", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "bucket", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "bucket", type_="foreignkey")
    op.drop_column("bucket", "user_id")
    # ### end Alembic commands ###
