"""add account access

Revision ID: 2788d0f24188
Revises: e2ba381d9c36
Create Date: 2023-12-12 18:37:16.286582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2788d0f24188'
down_revision: Union[str, None] = 'e2ba381d9c36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accountaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('is_institutional', sa.Boolean(), nullable=False),
    sa.Column('userinstitutionlink_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['userinstitutionlink_id'], ['userinstitutionlink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('account_user_id_fkey', 'account', type_='foreignkey')
    op.drop_constraint('account_userinstitutionlink_id_fkey', 'account', type_='foreignkey')
    op.drop_column('account', 'user_id')
    op.drop_column('account', 'userinstitutionlink_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('userinstitutionlink_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('account', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('account_userinstitutionlink_id_fkey', 'account', 'userinstitutionlink', ['userinstitutionlink_id'], ['id'])
    op.create_foreign_key('account_user_id_fkey', 'account', 'user', ['user_id'], ['id'])
    op.drop_table('accountaccess')
    # ### end Alembic commands ###
