"""add buckets

Revision ID: 3551606418b9
Revises: c35e5f35f56a
Create Date: 2024-03-28 15:25:58.361325

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3551606418b9"
down_revision: Union[str, None] = "c35e5f35f56a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bucket",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "account", sa.Column("default_bucket_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "account", "bucket", ["default_bucket_id"], ["id"])
    op.add_column("transaction", sa.Column("bucket_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transaction", "bucket", ["bucket_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "bucket_id")
    op.drop_constraint(None, "account", type_="foreignkey")
    op.drop_column("account", "default_bucket_id")
    op.drop_table("bucket")
    # ### end Alembic commands ###
