"""optional movement

Revision ID: 6865511ba6b5
Revises: fc4b92bac6db
Create Date: 2024-02-12 06:10:59.226214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6865511ba6b5"
down_revision: Union[str, None] = "fc4b92bac6db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account", "userinstitutionlink_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("account", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "transaction", "movement_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "movement_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column("account", "user_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "account", "userinstitutionlink_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
