"""remove BIC IBAN

Revision ID: 6dc8f33c0a7d
Revises: 91c4cb625f8b
Create Date: 2024-01-13 22:55:24.696269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dc8f33c0a7d'
down_revision: Union[str, None] = '91c4cb625f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('institutionalaccount', 'bic')
    op.drop_column('institutionalaccount', 'iban')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('institutionalaccount', sa.Column('iban', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('institutionalaccount', sa.Column('bic', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
