"""categories

Revision ID: 95912a207472
Revises: 2a70a877500c
Create Date: 2024-01-19 01:21:15.806833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95912a207472"
down_revision: Union[str, None] = "2a70a877500c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("plaid_id", sa.String(), nullable=True),
        sa.Column("plaid_metadata", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("icon", sa.LargeBinary(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("plaid_id"),
    )
    op.add_column("transaction", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "transaction", "category", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "transaction", type_="foreignkey")
    op.drop_column("transaction", "category_id")
    op.drop_table("category")
    # ### end Alembic commands ###
