"""nothing

Revision ID: 9f45f1fdbd8a
Revises: ede8727d25bb
Create Date: 2024-01-30 01:32:52.461215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f45f1fdbd8a"
down_revision: Union[str, None] = "ede8727d25bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "institutionalaccount",
        "type",
        existing_type=postgresql.ENUM(
            "INVESTMENT",
            "CREDIT",
            "DEPOSITORY",
            "LOAN",
            "BROKERAGE",
            "OTHER",
            name="institutionalaccounttype",
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "noninstitutionalaccount",
        "type",
        existing_type=postgresql.ENUM(
            "PERSONAL_LEDGER", "CASH", "PROPERTY", name="noninstitutionalaccounttype"
        ),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "noninstitutionalaccount",
        "type",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "PERSONAL_LEDGER", "CASH", "PROPERTY", name="noninstitutionalaccounttype"
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "institutionalaccount",
        "type",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "INVESTMENT",
            "CREDIT",
            "DEPOSITORY",
            "LOAN",
            "BROKERAGE",
            "OTHER",
            name="institutionalaccounttype",
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
