"""make buckets required

Revision ID: de8cc3124da5
Revises: 028ff3b73c20
Create Date: 2024-03-29 23:28:19.035356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de8cc3124da5"
down_revision: Union[str, None] = "028ff3b73c20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "account", "default_bucket_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "transaction", "bucket_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transaction", "bucket_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "account", "default_bucket_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
