"""merchants

Revision ID: ede8727d25bb
Revises: 07bf1b71c039
Create Date: 2024-01-25 00:14:02.181251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ede8727d25bb"
down_revision: Union[str, None] = "07bf1b71c039"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("default_category_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column("movement", sa.Column("merchant_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "movement", "merchant", ["merchant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "movement", type_="foreignkey")
    op.drop_column("movement", "merchant_id")
    op.drop_table("merchant")
    # ### end Alembic commands ###
