# Copyright (C) 2024 Alexandre Amat
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

name: Deploy to VPS

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: build

      - name: Cleanup VPS deployment directory
        env:
          PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          ssh ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }} "rm -rf /var/www/quartos/*"

      - name: Deploy to VPS
        env:
          PRIVATE_KEY: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          scp -r ./build/* ${{ vars.VPS_USERNAME }}@${{ vars.VPS_HOST }}:/var/www/quartos/

      - name: Cleanup local build artifacts
        run: |
          rm -rf ${{ github.workspace }}/build
          rm -f ~/.ssh/id_rsa
