name: Deploy Front End to GitHub Pages

on:
  push:
    branches:
      - main
    # paths:
    #   - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Build
        run: npm run build
        working-directory: frontend
        env:
          CI: ""

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: frontend/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Deploy to GitHub Pages
        run: |
          git checkout gh-pages
          rm -rf *
          mv -f ${{ runner.workspace }}/build/* .
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push
